(define make-iter
  (lambda ()
	(define i -1)
	(lambda ()
	  (set! i (+ i 1))
	  i)))
(define iter1 (make-iter))
(define iter2 (make-iter))
(display (iter1))
(display "\n")
(display (iter2))
(display "\n")
(display (iter1))
(display "\n")
(display (iter2))
(display "\n")
